name: Build and Release QEMU

on:
  push:
    tags:
      - '*'

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential pkg-config zlib1g-dev libglib2.0-dev libpixman-1-dev libfdt-dev ninja-build \
        libcap-ng-dev libattr1-dev

    - name: Configure and Build QEMU
      run: |
        mkdir qemu_build
        cd qemu_build
        ../configure  --target-list=x86_64-softmmu --enable-virtfs
        make -j$(nproc)
        cd ..
        tar czf qemu_build.tar.gz qemu_build

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACTION_ACCESS_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload QEMU binary as asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACTION_ACCESS_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./qemu_build.tar.gz
        asset_name: qemu_build.tar.gz
        asset_content_type: application/octet-stream
